// src/React/NetplayStats.tsx
import { Button } from "antd"
import { CloseOutlined, DashboardOutlined } from '@ant-design/icons'
import { useState } from "react"
import styled from "styled-components"
import { useTypedSelector } from "../redux/typedHooks"

const NetplayStatsContainer = styled.div`
  position: absolute;
  bottom: 5px;
  right: 5px;
`
const NetplayStatsPanel = styled.div`
  background-color: rgba(255, 255, 255, 0.75);
  border-radius: 3px;
  box-shadow: 0 2px 8px 0px rgba(0, 0, 0, 0.3);

  padding: 4px;
  display: flex;
  flex-direction: column;
  align-items: flex-end;

  td {
    padding: 0 2px;
  }
`
const NetplayStatsTable = styled.table`
  //table-layout: fixed;
`

export const NetplayStats = () => {
  const { netplayStats } = useTypedSelector((state) => ({
    netplayStats: state.netplay
  }))

  const [menuOpen, setMenuOpen] = useState(false)

  if (netplayStats.ping === null) {
    return null
  }


  
  return (
    <NetplayStatsContainer>
      { menuOpen
        ? (
        <NetplayStatsPanel>
          <Button
            icon={<CloseOutlined />}
            style={{
              
            }}
            onClick={() => setMenuOpen(false)} />
          <NetplayStatsTable>
            <tr>
              <td>Ping</td>
              <td>{netplayStats.ping ? `${netplayStats.ping}ms +/- ${netplayStats.pingStdDev}ms` : null}</td>
            </tr>
            <tr>
              <td>History Length</td>
              <td>{netplayStats.historyLength}</td>
            </tr>
            <tr>
              <td>Largest Future Size</td>
              <td>{netplayStats.largestFutureSize}</td>
            </tr>
            <tr>
              <td>Predicted Frames</td>
              <td>{netplayStats.predictedFrames}</td>
            </tr>
            <tr>
              <td>Stalling</td>
              <td>{netplayStats.stalling.toString()}</td>
            </tr>
          </NetplayStatsTable>
        </NetplayStatsPanel>
      )
      : <Button icon={<DashboardOutlined />} onClick={() => setMenuOpen(true)}/>
    }
    </NetplayStatsContainer>
  )
}

// src/Vue/components/NetplayStats.vue
<template>
  <div class="netplay-stats-wrapper">
    <card-box>
      <table class="netplay-stats-table">
        <span v-if="!!this.vueService.state.netplay.errorMessage">
          {{this.vueService.state.netplay.errorMessage}}
        </span>
        <tr>
          <td>Ping</td>
          <td>{{this.ping}}</td>
        </tr>
        <tr>
          <td>History Length</td>
          <td>{{this.vueService.state.netplay.historyLength}}</td>
        </tr>
        <tr>
          <td>Frame</td>
          <td>{{this.vueService.state.netplay.frame}}</td>
        </tr>
        <tr>
          <td>Largest Future Size</td>
          <td>{{this.vueService.state.netplay.largestFutureSize}}</td>
        </tr>
        <tr>
          <td>Predicted Frames</td>
          <td>{{this.vueService.state.netplay.predictedFrames}}</td>
        </tr>
        <tr>
          <td>Stalling</td>
          <td>{{this.vueService.state.netplay.stalling}}</td>
        </tr>
      </table>
    </card-box>
  </div>
</template>

<script lang="ts">
import { VueService } from "@/Game/VueService/VueService";
import Vue from "vue";
import CardBox from "./CardBox.vue";

export default Vue.extend({
  components: { CardBox },
  name: "NetplayStats",
  data: function() {
    return {
      vueService: VueService
    }
  },
  computed: {
    ping() {
      const ping = this.vueService.state.netplay.ping
      if (ping !== null) {
        return `${ping}ms +/- ${this.vueService.state.netplay.pingStdDev}ms`
      }
      return null
    }
  }
});
</script>

<style scoped lang="scss">
.netplay-stats-wrapper {
  position: absolute;
  bottom: 5px;
  right: 5px;
}
.netplay-stats-table {
  //table-layout: fixed;
  width: 300px;
}
</style>
