// src/Vue/components/AspectRatioLetterbox.vue
<template>
  <div :class="this.shouldUseHorizontalLetterbox ? 'aspect-ratio-wrapper-h' : 'aspect-ratio-wrapper-v'" ref="aspectRatioWrapper">
    <div :class="this.shouldUseHorizontalLetterbox ? 'aspect-ratio-div-h' : 'aspect-ratio-div-v'">
      <div class="content-wrapper">
        <game-canvas />
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import GameCanvas from "./GameCanvas.vue"

// forces 16:9. Not using consts for 16:9 because css is involved 

export default Vue.extend({
  name: "AspectRatioLetterbox",
  components: { GameCanvas },
  data: function() {
    return {
      shouldUseHorizontalLetterbox: true
    }
  },
	methods: {
		detectWidth() {
			const aspectRatioWrapperElement = this.$refs.aspectRatioWrapper as Element;
      const contentWrapperAspectRatio = aspectRatioWrapperElement.clientWidth / aspectRatioWrapperElement.clientHeight
			this.shouldUseHorizontalLetterbox = contentWrapperAspectRatio >= (16 / 9);
		}
	},
	mounted() {
		this.detectWidth();
		window.onresize = this.detectWidth.bind(this);
	}
});
</script>

<style scoped lang="scss">
.aspect-ratio-wrapper-h,
.aspect-ratio-wrapper-v {
  position: relative;
  width: 100%;
  height: 100%;

  display: flex;
  justify-content: center;
  align-items: center;

  background-color: rgb(88, 223, 166);
}

.aspect-ratio-wrapper-h {
  writing-mode: vertical-lr;
}

.aspect-ratio-div-h,
.aspect-ratio-div-v {
  position: relative;
  box-sizing: content-box;
}

.aspect-ratio-div-h {
  $height-percent: 100%;
  height: $height-percent;
  width: 0;
  padding-right: calc(#{$height-percent} * (16 / 9));
}
.aspect-ratio-div-v {
  $width-percent: 100%;
  width: $width-percent;
  height: 0;
  padding-bottom: calc(#{$width-percent} * (9 / 16));
}

.content-wrapper {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  writing-mode: horizontal-tb;
}
</style>

// src/React/AspectRatioLetterbox.tsx
import { ReactNode, useCallback, useEffect, useRef, useState } from "react";
import styled, { css } from "styled-components";

const AspectRatioWrapper = styled.div<{ horizontal: boolean }>` //todo rename this param once I understand what it does
  position: relative;
  width: 100%;
  height: 100%;

  display: flex;
  justify-content: center;
  align-items: center;

  /* background-color: rgb(50, 119, 90); */

  ${props => props.horizontal && css`
    writing-mode: vertical-lr;
  `}
`

const AspectRatioDiv = styled.div<{ horizontal: boolean }>`
  position: relative;
  box-sizing: content-box;

  ${props => props.horizontal ? css`
    height: 100%;
    width: 0;
    padding-right: calc(100% * (16 / 9));
  ` : css`
    width: 100%;
    height: 0;
    padding-bottom: calc(100% * (9 / 16));
  `}
`
const ContentWrapper = styled.div`
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  writing-mode: horizontal-tb;
`

export type AspectRatioLetterboxProps = {
  children?: ReactNode;
}

export const AspectRatioLetterbox = ({children}: AspectRatioLetterboxProps) => {
  const [shouldUseHorizontalLetterbox, setShouldUseHorizontalLetterbox] = useState(true)
  const aspectRatioWrapper = useRef<HTMLDivElement | null>(null)
  const detectWidth = useCallback(() => {
    const aspectRatioWrapperElement = aspectRatioWrapper.current
    if (aspectRatioWrapperElement) {
      const contentWrapperAspectRatio = aspectRatioWrapperElement.clientWidth / aspectRatioWrapperElement.clientHeight
      setShouldUseHorizontalLetterbox(contentWrapperAspectRatio >= (16 / 9))
    }
  }, [])
  useEffect(() => {
    detectWidth();
		window.addEventListener('resize', detectWidth)
    return () => {
      window.removeEventListener('resize', detectWidth)
    }
  })

  return (
    <AspectRatioWrapper
      horizontal={shouldUseHorizontalLetterbox}
      ref={aspectRatioWrapper}
    >
      <AspectRatioDiv horizontal={shouldUseHorizontalLetterbox}>
        <ContentWrapper>
          {children}
        </ContentWrapper>
      </AspectRatioDiv>
    </AspectRatioWrapper>
  )
}
