// src/Vue/components/NetplayMenu.tsx
// <template>
//   <div class="netplay-menu-wrapper">
//     <card-box>
//       <div class="netplay-menu-column">
//         <button @click="copyToClipboard">
//           Copy Player 2 Link to Clipboard
//         </button>
//         <a :href="this.vueService.state.netplay.joinUrl" target="_blank">
//           Open Player 2 Tab
//         </a>
//       </div>
//     </card-box>
//   </div>
// </template>

// <script lang="ts">
// import { VueService } from "@/Game/VueService/VueService";
// import Vue from "vue";
// import CardBox from "./CardBox.vue";

// export default Vue.extend({
//   components: { CardBox },
//   name: "NetplayMenu",
//   data: function() {
//     return {
//       vueService: VueService
//     }
//   },
//   computed: {
//     displayNumber() {
//       console.log(this.vueService.state.netplay)
//       return 'some value'
//     }
//   },
//   methods: {
//     copyToClipboard() {
//       window.navigator.clipboard.writeText(this.vueService.state.netplay.joinUrl)
//     }
//   }
// });
// </script>

// <style scoped lang="scss">
// .netplay-menu-wrapper {
//   position: absolute;
//   bottom: 5px;
//   left: 5px;
// }
// .netplay-menu-column {
//   display: flex;
//   flex-direction: column;
//   align-items: center;
//   :not(:last-child) {
//     margin-bottom: 8px;
//   }
//   padding: 4px;
// }
// </style>

// src/React/NetplayMenu.tsx
import { Button, Card } from "antd"
import { useCallback } from "react"
import { useSelector, useStore } from "react-redux"
import styled from "styled-components"
import { AppState } from "../redux/reducer"
import { useTypedSelector } from "../redux/typedHooks"

const NetplayMenuWrapper = styled.div`
  position: absolute;
  bottom: 5px;
  left: 5px;
`

const NetplayMenuColumn = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  :not(:last-child) {
    margin-bottom: 8px;
  }
  padding: 4px;
`

export const NetplayMenu = () => {

  const { joinUrl } = useTypedSelector(({netplay}) => {
    return {
      joinUrl: netplay.joinUrl
    }
  })

  const copyToClipboard = useCallback(() => {
    if (joinUrl) {
      window.navigator.clipboard.writeText(joinUrl)
    }
  }, [joinUrl])

  return (
    <NetplayMenuWrapper>
      <Card>
        <NetplayMenuColumn>
        <Button onClick={copyToClipboard}>
          Copy Player 2 Link to Clipboard
        </Button>
        </NetplayMenuColumn>
      </Card>
    </NetplayMenuWrapper>
  )
}
